# Jekyll
markdown: rdiscount
highlighter: "pygments"
permalink: /:title.html

# Conference info
conf:
   name: "HISS 2015"
   description: "High Integrity Systems Symposium"
   date: "June 3, 2015"
   price: "Participation is open and free* - Register by May 26th!"
   address: "Simula Research Laboratory, Martin Linges vei 25, Fornebu, Norway (3rd floor of Terminalbygget, IT Fornebu/Technopolis)"
   mappointer-override: "Simula+Research+Laboratory/@59.8953574,10.6291997"
   venue: "Simula Research Laboratory"
   city: "Oslo, Norway"
   directions: 
    - 
      p: "Simula can be easily reached by public transport or by car. From Oslo Airport, there is a direct train connection to Lysaker station, and a short ~5-10min busride from there. Hotels are available both in Oslo centre, and in the near surroundings of Simula." 
    -
      p: "<strong>Directions by Public Transport:</strong> Take the train to Skøyen or Lysaker station which both have regular bus departures to Fornebu. The following bus routes stop at IT Fornebu: 28, 24, 31, 31E and 36E. If you are going by bus directly from the centre of Oslo, bus 31E or 36E are the fastest. The bus stop closest to Simula is called 'IT Fornebu'. For more information and schedules look at <a href=http://www.trafikanten.no/>Ruter</a> or call 177 (within Oslo/Akershus)."
    -
      p: "After you exit the bus, you will see the orange hub in the middle of 'Portalbygget'. You need to walk down the stairs beneath it to get to the main entrance hall ('Kai Fjell-hallen' / 'Resepsjon') of 'Terminalbygget'. Take the stairs that go up right before the reception, and you will find Simulas main entrance on the 3rd floor.  Please ring the bell and we will open for you. If you need to use the elevator, call Simula at 67 82 82 00. Please ask for directions in IT Fornebu's reception." 
    - 
      p: "<strong>Directions by Car:</strong> Follow directions towards Fornebu and then follow the signs for Snarøya. After you have passed the Telenor building, follow the road straight ahead through a junction and then take the second exit  ('Rolfsbuktveien') at the first roundabout. Drive past the orange hub/building and take the first turn left at the corner of the HP-builing. Guests can park for a fee in the underground parking house between 'Terminalbygget' and the new Statoil building. Take the stairs/lift up and walk to the reception. From there you can follow the directions given above. Keep in mind that driving patterns may change due to the construction work going on at IT Fornebu."

# Site info
site:
  url: "http://high-integrity-systems.no"
  favicon: "img/favicon.png"
  googleanalytics: ""
  images:
    cover: "img/background.jpg"

subscribe_text: "Register now"
subscribe_url: "https://docs.google.com/forms/d/19HlHBGpCffhjksMH9SO0HWff309rBEZNb_wuxvQFIlE/viewform?usp=send_form"

# Active sections on the website
sections:
  about: true
  c4p: false
  location: true
  speakers: true
  schedule: true
  supporters: true
  partners: true
  contact: true

# Schedule section
schedule_section:
   title: "(Tentative) Schedule"
   text: "While we are working out the speaker details, the schedule below provides an impression of the overall program / topics we aim at."
   time: "Time"
   slot: "Slot"
   description: "Description"

# The entire schedule
schedule:
  -
    name: "Check-in"
    time: "9h00"
  -
    name: "Opening & Welcome"
    time: "9h15"
    description: "Description of opening speakers"
  -
    name: "Tim Kelly"
    photo: "img/tim_kelly.png"
    bio: "Tim Kelly is Professor of High Integrity Systems within the Department of Computer Science at the University of York. He is perhaps best known for his work on system and software safety case development, particularly his work on refining and extending the Goal Structuring Notation (GSN). His research interests include safety case management, software safety analysis and justification, software architecture safety, certification of adaptive and learning systems, and the dependability of “Systems of Systems”. He has supervised many research projects in these areas with funding and support from Airbus, BAE SYSTEMS, Data Systems and Solutions, DTI, EPSRC, ERA Technology, Ministry of Defence, QinetiQ and Rolls-Royce. He has published over 150 papers on high integrity systems development and justification in international journals and conferences."
    company: "University of York, UK"
    email: "tim.kelly@york.ac.uk"
    presentation:
      title: "Keynote: Fundamental Principles of Software Safety Assurance"
      description: "There are many standards that either directly or indirectly address the development and assurance of safety-critical software (e.g. ISO 26262 for the automotive domain, EN 50128 for the railway domain, and DO-178B/C in the aerospace domain). There are easily observed differences in the details of these standards. For example, DO-178B uses the concept of Development Assurance Levels (DALs) to moderate the objectives of the standard according to the criticality of the software under development, whereas IEC 61508 uses the concept of Safety Integrity Levels (SILs) to make recommendations as to suitable design and assurance techniques according to the criticality of the software under development. The requirements and recommendations for SILs in IEC 61508 are not the same as those for DALs in DO-178B. However, underlying these differences there are a number of fundamental principles that can be observed in many of the current standards. Using a framework of 4+1 principles of software safety, this talk will discuss the essential features and challenges of current safety-critical software development.
"
      time: "9h30"
  -
    name: "Coffee-break"
    time: "10h30"
  -
    name: "Name Speaker #1"
    photo: "img/brown_woman.png"
    bio: "Bio of speaker 1."
    company: "Affiliation"
    twitter: "twitterhandle"
    presentation:
      title: "Challenges High Integrity Systems in the Maritime Industry"
      description: "Abstract"
      time: "11h00"
  -
    name: "Name Speaker #2"
    photo: "img/orange_boy.png"
    bio: "Bio of speaker 2."
    company: "Affiliation"
    email: "mail@there.io"
    presentation:
      title: "Ensuring Safety of Robots"
      description: "Abstract"
      time: "11h30"
  -
    name: "Lunch"
    time: "12h00"
  -
    name: "Harold Thimbleby"
    photo: "img/harold_thimbleby.jpg"
    bio: "Harold Thimbleby is professor of computer science at Swansea University, Wales. His passion is designing dependable systems to accommodate human error, especially in healthcare. Harold is an Honorary Fellow of the Royal College of Physicians, a Fellow of the Royal College of Physicians, Edinburgh, the Institute of Engineering Technology, the Learned Society of Wales, and an Honorary Fellow of the Royal Society of Arts. He is a visiting professor at UCL and at Middlesex University and has been a Royal Society Wolfson Research Merit award holder and a Royal Society Leverhulme Trust Senior Research Fellow. He is Emeritus Gresham Professor of Geometry."
    company: "Swansea University, Wales"
    presentation:
      title: "Designing IT to make healthcare safer"
      description: "Abstract will be added soon"
      time: "13h00"
  -
    name: "Lillian Røstad"
    photo: "img/lillian_rostad.jpg"
    bio: "Bio of speaker 4."
    company: "Agency for Public Management and eGovernment (Difi), Norway"
    presentation:
      title: "Software Security in eGovernment"
      description: "Abstract will be added soon"
      time: "13h30"
  -
    name: "Name Speaker #5"
    photo: "img/white_woman.png"
    bio: "Bio of speaker 5."
    company: "Affiliation"
    twitter: "twitterhandle"
    presentation:
      title: "Safety Assessment of High Energy Systems"
      description: "Abstract"
      time: "14h00"
  -
    name: "Coffee-break"
    time: "14h30"
  -
    name: "Name Speaker #6"
    photo: "img/orange_girl.png"
    bio: "Bio of speaker 6."
    company: "Affiliation"
    twitter: "twitterhandle"
    presentation:
      title: "Towards better Certification Practices in Avionics"
      description: "Abstract"
      time: "15h00"
  -
    name: "Ahmed Elmokashfi"
    photo: "img/ahmed_elmokashfi.jpg"
    bio: "Bio of Ahmed will be added soon"
    company: "Simula Research Laboratory, Norway"
    presentation:
      title: "Towards Robust Communication Infrastructures"
      description: "Abstract will be added soon"
      time: "15h30"
  -
    name: "Panelists"
    photo: "img/discussion-icon.png"
    bio: "Names and affiliation / short bio of initial panelists."
    presentation:
      title: "Fishbowl Panel Discussion"
      description: "Description of the panel format/procedure: 'Fishbowl' rotating panel."
      time: "16h00"
  -
    name: "Wrap-up"
    time: "17h00"

# List of Supporters
supporters:

# List of Partners (same format as supporters)
partners:
  -
    name: "Simula Research Laboratory"
    logo: "img/simula-logo.png"
    url: "https://simula.no"
  -
    name: "Certus Center for Research-based Innovation"
    logo: "img/certus-logo.png"
    url: "https://certus-sfi.no"
  -
    name: "Institute for Energy Technology"
    logo: "img/ife-logo.png"
    url: "http://ife.no/en"
  -
    name: "Bergen Language Design Laboratory"
    logo: "img/bldl-logo.png"
    url: "https://bldl.ii.uib.no/"


# About section
about_section:
   title: "About"
   description: 
    - 
      p: "Software has become an essential part of our critical national infrastructure, such as transport systems, banking industries, and energy generation, and a key element in devices in the medical and automotive sector. The failure of such software-based systems can have profound consequences both for individuals and for companies that are responsible for delivering such software."
    -
      p: "High integrity software and system engineering used to be the realm of avionics and the military, but with today's highly-interconnected and mobile systems, it is increasingly needed for common  applications to be able to demonstrate their reliability, robustness, safety, security and maintainability. As such, sound technologies that can address these high integrity concerns in an efficient manner are one of today’s key engineering challenges. "
    -
      p: "The one day High Integrity Systems Symposium will be held at Simula in the first week of June 2015. It will will feature keynote talks from leading experts, presentations on current technology and experiences by researchers and practitioners, as well as a call for action to organize high integrity stakeholders in a national High Integrity Systems Forum.  We aim at 50-80 participants, mostly from Norway, with an equal mix of industrial and academic participants. We also aim at inviting a small number (4-5) of high profile international experts in the field, either as keynote speaker or as discussion leader."
    - 
      p: "HISS 2015 builds on the success of the <a href=http://www.uib.no/ii/59562/bldl-high-integrity-day>2014 High Integrity Day</a>."
    -
      p: "* Please note that space is limited and attendance is by registration only. We recommend holding off on travel and accommodation bookings until you receive the confirmation of registration from the workshop organisers, to avoid disappointment. There is no attendance fee. However, please appreciate that space is limited and catering needs to be booked in advance. For this reason, even though participation to the workshop is free of charge, there will be a cancellation fee of NOK 1000 for those who register but subsequently do not attend."

# Call for papers section (unused for HISS 2015)
c4p_section:
   title: "Call for papers"
   text: "We want your papers. Topics of interest include...."
   c4p_url: "http://call4papers.url"
   c4p_caption: "Submit"
   c4p_rules_url: "http://call4paperz.url/guidelines/"
   c4p_rules_caption: "Guidelines for submission."

# Contact section
contact_section:
   title: "Organizers"
   text: "Contact us if you have any questions."
   contacts:
   -
     title: "Leon Moonen (Simula Research Laboratory)"
     email: "leon.moonen@computer.org"
   -
     title: "Sunil Nair (Institute for Energy Technology)"
     email: "Sunil.Nair@ife.no"

   email: "leon.moonen@computer.org"
   twitter_url: "http://twitter.com/your_twitter"
   twitter_username: "@your_twitter"
   show_form: false
   form:
     action: "contact-form.php"
     name: "What's your name?"
     email: "What's your email?"
     message: "Write a message"
     send_button: "Send"


# Location section
location_section:
   title: "Location"

# Speakers section
speakers_section:
   title: "Speakers"

# Partners section
partners_section:
   title: "Partners"
   show_your_logo_here: false

# supporters section
supporters_section:
   title: "Sponsors"
   show_your_logo_here: true